### ISSUE TITLE
grunt-browserify

### ISSUE THREAD

**Issue by monolithed** [Bockit/cacheify#10]
Could you provide an example with `grunt-browserify`?

``` js
{
    transform: [
        [
            'babelify', { }
        ]
    ]
},

files: {}
```

**Comment by Bockit** [comment]
Sorry that I never got to this. It had been a while then, and even longer since that I used Grunt, I'm afraid I've forgotten everything. Anyone is welcome to make a PR but I'm going to close the issue for me sorry.
